baseurl = "/"
languageCode = "de-de"
title = "Familie Husić"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Hrvoje Husić"
	description = "Die internationale Familie"
	copyright = "Familie Husić"

	# Repository
	provider = "All-Inkl"
	#repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = ""
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = ["css/external-link.css", "pro-adblock/assets/css/padb-style-1.css"]
	custom_js  = ["js/jquery-3.1.0.slim.min.js", "js/jquery.cookie.js", "js/cookieConsent.js", "js/cookieconsent.min.js", "js/proAdBlock.js", "js/gads.js"]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "cyan"
    	accent  = "deep purple"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = ""


[[menu.main]]
	name   = "Familie Husić"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Japan"
	url    = "japan/"
	weight = 100

[[menu.main]]
	name   = "Über uns"
	url    = "ueber-uns/"
	weight = 200

[[menu.main]]
	name   = "Kontakt"
	url    = "kontakt/"
	weight = 300


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
