version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.16
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Download Hugo"
          command: wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.18.1/hugo_0.18.1-64bit.deb
      - run:
          name: "Install Hugo"
          command: sudo dpkg -i /tmp/hugo.deb
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - add_ssh_keys
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo 'example.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJiGRY6N9WYQ0vy6cTiwAgNbc6ueJmVo/EafBtmT7bcD6cQMbipYM/KfYQ2lCn2TxqWepZKYoyoVQXgArycCOns=' >> ~/.ssh/known_hosts
              rsync -va --delete public/ staticweb@example.com:/var/www/
            fi
